---
title: "Merge all the imdb datasets into one file"
output: html_document
date: "2023-09-19"
---
In this RMarkdown file the datasets from imdb are merged and filtered.

```{r}
library(dplyr)

#Merge imdb_basics_data and imdb_crew_data on the variable 'tconst'
imdb_basics_crew <- left_join(imdb_basics_data, imdb_crew_data, by="tconst")

#Rename the variable 'directors' to 'nconsts' since it's an array of nconsts
imdb_basics_crew <- imdb_basics_crew %>%
  rename(nconst = directors)

#Merge the dataframe that was created above with the imdb_name_basics data
imdb_basics_crew_name <- left_join(imdb_basics_crew, imdb_name_basics, by= "nconst")

#Delete all variables that won't be used in the project
imdb_basics_crew_name <- imdb_basics_crew_name %>%
  select(-endYear, -writers, -birthYear, -deathYear)

#See all unique values of the titleType
unique_values <- unique(imdb_basics_crew_name$titleType)

print(unique_values)

#Select only the data that contains titleType movie
filtered_data <- imdb_basics_crew_name %>% filter(titleType == "movie")
```
```{r}

merged_dataset <- opening_weekend %>% left_join(imdb_basics_crew_name, by = c("name" = "primaryTitle"))

```

```{r}
# Find duplicated ride_ids
merged_dataset %>% 
  count(name) %>% 
  filter(n > 1)

# Remove full and partial duplicates
merged_dataset_unique <- merged_dataset %>%
  # Only based on ride_id instead of all cols
  distinct(name, .keep_all = TRUE)

# Find duplicated ride_ids in bike_share_rides_unique
merged_dataset_unique %>%
  # Count the number of occurrences of each ride_id
  count(name) %>%
  # Filter for rows with a count > 1
  filter(n > 1)

```



```{r}
csv_bestand <- "merged_dataset_unique.csv"

write.csv(merged_dataset_unique, file = csv_bestand, row.names = FALSE)

cat("Het dataframe is opgeslagen als", csv_bestand, "\n")



``` 